#Requires -Version 5.1
<#
.SYNOPSIS
  Generates Malx_AI/Mcp/McpOAuthBuiltIns.Generated.cs from local OAuth app credential files.

.DESCRIPTION
  Reads client id/secret text files from (first hit wins per file):
	%LOCALAPPDATA%\Axiom\SharedOAuth
	%LOCALAPPDATA%\Axiom-Dev
	%LOCALAPPDATA%\Axiom

  Writes a gitignored partial class used by Release/publish so end-user Connect works
  without requiring each user to create OAuth apps. Never commit the generated file.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\scripts\Generate-McpOAuthBuiltIns.ps1
#>
[CmdletBinding()]
param(
	[string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Read-CredentialFile {
	param(
		[string[]]$Roots,
		[string]$FileName
	)

	foreach ($root in $Roots) {
		if ([string]::IsNullOrWhiteSpace($root) -or -not (Test-Path -LiteralPath $root)) {
			continue
		}
		$path = Join-Path $root $FileName
		if (-not (Test-Path -LiteralPath $path)) {
			continue
		}
		$text = (Get-Content -LiteralPath $path -Raw -ErrorAction SilentlyContinue)
		if ($null -eq $text) {
			continue
		}
		$trimmed = $text.Trim()
		if (-not [string]::IsNullOrWhiteSpace($trimmed)) {
			return $trimmed
		}
	}

	return ""
}

function ConvertTo-CSharpVerbatim {
	param([string]$Value)
	if ($null -eq $Value) {
		return ""
	}
	return $Value.Replace('"', '""')
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
	$OutputPath = Join-Path $repoRoot "Malx_AI\Mcp\McpOAuthBuiltIns.Generated.cs"
}

$local = $env:LOCALAPPDATA
$roots = @(
	(Join-Path $local "Axiom\SharedOAuth"),
	(Join-Path $local "Axiom-Dev"),
	(Join-Path $local "Axiom")
)

$googleId = Read-CredentialFile -Roots $roots -FileName "google_oauth_client_id.txt"
$googleSecret = Read-CredentialFile -Roots $roots -FileName "google_oauth_client_secret.txt"
$githubId = Read-CredentialFile -Roots $roots -FileName "github_oauth_client_id.txt"
$todoistId = Read-CredentialFile -Roots $roots -FileName "todoist_client_id.txt"
$todoistSecret = Read-CredentialFile -Roots $roots -FileName "todoist_client_secret.txt"

# GitHub's client secret is intentionally never embedded here. Unlike Google's Desktop-app
# secret (documented non-confidential) and Todoist's (required by its token endpoint), a
# GitHub OAuth App secret is a confidential-client credential. The device flow this app uses
# only ever sends client_id (see GitHubOAuthService.AuthorizeDeviceAsync), so there is nothing
# to gain from shipping it and real cost if a distributed binary is unzipped and it leaks:
# every installed copy needs the secret rotated. Local dev can still use
# github_oauth_client_secret.txt / AXIOM_GITHUB_OAUTH_CLIENT_SECRET via McpOAuthConfig; that
# path is untouched by this script.

$present = @()
if ($googleId) { $present += "Google" }
if ($githubId) { $present += "GitHub" }
if ($todoistId) { $present += "Todoist" }

if ($present.Count -eq 0) {
	Write-Warning "No OAuth app credentials found under SharedOAuth / Axiom-Dev / Axiom. Generated built-ins will be empty."
}

$gId = ConvertTo-CSharpVerbatim $googleId
$gSec = ConvertTo-CSharpVerbatim $googleSecret
$ghId = ConvertTo-CSharpVerbatim $githubId
$tId = ConvertTo-CSharpVerbatim $todoistId
$tSec = ConvertTo-CSharpVerbatim $todoistSecret

$generated = @"
// <auto-generated />
// DO NOT COMMIT. Generated by scripts/Generate-McpOAuthBuiltIns.ps1 for release packaging.
namespace Malx_AI.Mcp
{
	internal static partial class McpOAuthBuiltIns
	{
		static partial void TryGetGoogleClientId(ref string value) { value = @"$gId"; }
		static partial void TryGetGoogleClientSecret(ref string value) { value = @"$gSec"; }
		static partial void TryGetGitHubClientId(ref string value) { value = @"$ghId"; }
		// Intentionally not embedded - GitHub's device flow never needs a client secret.
		// See comment above. Local dev can still supply one via file/env override.
		static partial void TryGetGitHubClientSecret(ref string value) { }
		static partial void TryGetTodoistClientId(ref string value) { value = @"$tId"; }
		static partial void TryGetTodoistClientSecret(ref string value) { value = @"$tSec"; }
	}
}
"@

$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) {
	New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $generated -Encoding UTF8
Write-Host "Wrote $OutputPath"
Write-Host ("Providers embedded: " + ($(if ($present.Count -gt 0) { ($present -join ", ") } else { "(none)" })))
